// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: proto/rating.proto

package rating

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "loveguru/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Rating        int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	ReviewText    string                 `protobuf:"bytes,3,opt,name=review_text,json=reviewText,proto3" json:"review_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRatingRequest) Reset() {
	*x = CreateRatingRequest{}
	mi := &file_proto_rating_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRatingRequest) ProtoMessage() {}

func (x *CreateRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRatingRequest.ProtoReflect.Descriptor instead.
func (*CreateRatingRequest) Descriptor() ([]byte, []int) {
	return file_proto_rating_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRatingRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateRatingRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateRatingRequest) GetReviewText() string {
	if x != nil {
		return x.ReviewText
	}
	return ""
}

type CreateRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rating        *common.Rating         `protobuf:"bytes,1,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRatingResponse) Reset() {
	*x = CreateRatingResponse{}
	mi := &file_proto_rating_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRatingResponse) ProtoMessage() {}

func (x *CreateRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRatingResponse.ProtoReflect.Descriptor instead.
func (*CreateRatingResponse) Descriptor() ([]byte, []int) {
	return file_proto_rating_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRatingResponse) GetRating() *common.Rating {
	if x != nil {
		return x.Rating
	}
	return nil
}

type GetAdvisorRatingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdvisorId     string                 `protobuf:"bytes,1,opt,name=advisor_id,json=advisorId,proto3" json:"advisor_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdvisorRatingsRequest) Reset() {
	*x = GetAdvisorRatingsRequest{}
	mi := &file_proto_rating_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdvisorRatingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdvisorRatingsRequest) ProtoMessage() {}

func (x *GetAdvisorRatingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdvisorRatingsRequest.ProtoReflect.Descriptor instead.
func (*GetAdvisorRatingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_rating_proto_rawDescGZIP(), []int{2}
}

func (x *GetAdvisorRatingsRequest) GetAdvisorId() string {
	if x != nil {
		return x.AdvisorId
	}
	return ""
}

func (x *GetAdvisorRatingsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAdvisorRatingsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetAdvisorRatingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ratings       []*common.Rating       `protobuf:"bytes,1,rep,name=ratings,proto3" json:"ratings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdvisorRatingsResponse) Reset() {
	*x = GetAdvisorRatingsResponse{}
	mi := &file_proto_rating_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdvisorRatingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdvisorRatingsResponse) ProtoMessage() {}

func (x *GetAdvisorRatingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdvisorRatingsResponse.ProtoReflect.Descriptor instead.
func (*GetAdvisorRatingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_rating_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdvisorRatingsResponse) GetRatings() []*common.Rating {
	if x != nil {
		return x.Ratings
	}
	return nil
}

var File_proto_rating_proto protoreflect.FileDescriptor

const file_proto_rating_proto_rawDesc = "" +
	"\n" +
	"\x12proto/rating.proto\x12\x0floveguru.rating\x1a\x12proto/common.proto\"m\n" +
	"\x13CreateRatingRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12\x1f\n" +
	"\vreview_text\x18\x03 \x01(\tR\n" +
	"reviewText\"G\n" +
	"\x14CreateRatingResponse\x12/\n" +
	"\x06rating\x18\x01 \x01(\v2\x17.loveguru.common.RatingR\x06rating\"g\n" +
	"\x18GetAdvisorRatingsRequest\x12\x1d\n" +
	"\n" +
	"advisor_id\x18\x01 \x01(\tR\tadvisorId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"N\n" +
	"\x19GetAdvisorRatingsResponse\x121\n" +
	"\aratings\x18\x01 \x03(\v2\x17.loveguru.common.RatingR\aratings2\xd8\x01\n" +
	"\rRatingService\x12[\n" +
	"\fCreateRating\x12$.loveguru.rating.CreateRatingRequest\x1a%.loveguru.rating.CreateRatingResponse\x12j\n" +
	"\x11GetAdvisorRatings\x12).loveguru.rating.GetAdvisorRatingsRequest\x1a*.loveguru.rating.GetAdvisorRatingsResponseB\x17Z\x15loveguru/proto/ratingb\x06proto3"

var (
	file_proto_rating_proto_rawDescOnce sync.Once
	file_proto_rating_proto_rawDescData []byte
)

func file_proto_rating_proto_rawDescGZIP() []byte {
	file_proto_rating_proto_rawDescOnce.Do(func() {
		file_proto_rating_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rating_proto_rawDesc), len(file_proto_rating_proto_rawDesc)))
	})
	return file_proto_rating_proto_rawDescData
}

var file_proto_rating_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_rating_proto_goTypes = []any{
	(*CreateRatingRequest)(nil),       // 0: loveguru.rating.CreateRatingRequest
	(*CreateRatingResponse)(nil),      // 1: loveguru.rating.CreateRatingResponse
	(*GetAdvisorRatingsRequest)(nil),  // 2: loveguru.rating.GetAdvisorRatingsRequest
	(*GetAdvisorRatingsResponse)(nil), // 3: loveguru.rating.GetAdvisorRatingsResponse
	(*common.Rating)(nil),             // 4: loveguru.common.Rating
}
var file_proto_rating_proto_depIdxs = []int32{
	4, // 0: loveguru.rating.CreateRatingResponse.rating:type_name -> loveguru.common.Rating
	4, // 1: loveguru.rating.GetAdvisorRatingsResponse.ratings:type_name -> loveguru.common.Rating
	0, // 2: loveguru.rating.RatingService.CreateRating:input_type -> loveguru.rating.CreateRatingRequest
	2, // 3: loveguru.rating.RatingService.GetAdvisorRatings:input_type -> loveguru.rating.GetAdvisorRatingsRequest
	1, // 4: loveguru.rating.RatingService.CreateRating:output_type -> loveguru.rating.CreateRatingResponse
	3, // 5: loveguru.rating.RatingService.GetAdvisorRatings:output_type -> loveguru.rating.GetAdvisorRatingsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_rating_proto_init() }
func file_proto_rating_proto_init() {
	if File_proto_rating_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rating_proto_rawDesc), len(file_proto_rating_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rating_proto_goTypes,
		DependencyIndexes: file_proto_rating_proto_depIdxs,
		MessageInfos:      file_proto_rating_proto_msgTypes,
	}.Build()
	File_proto_rating_proto = out.File
	file_proto_rating_proto_goTypes = nil
	file_proto_rating_proto_depIdxs = nil
}
