// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.28.3
// source: proto/advisor.proto

package advisor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdvisorService_ListAdvisors_FullMethodName   = "/loveguru.advisor.AdvisorService/ListAdvisors"
	AdvisorService_GetAdvisor_FullMethodName     = "/loveguru.advisor.AdvisorService/GetAdvisor"
	AdvisorService_ApplyAsAdvisor_FullMethodName = "/loveguru.advisor.AdvisorService/ApplyAsAdvisor"
	AdvisorService_UpdateProfile_FullMethodName  = "/loveguru.advisor.AdvisorService/UpdateProfile"
)

// AdvisorServiceClient is the client API for AdvisorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdvisorServiceClient interface {
	ListAdvisors(ctx context.Context, in *ListAdvisorsRequest, opts ...grpc.CallOption) (*ListAdvisorsResponse, error)
	GetAdvisor(ctx context.Context, in *GetAdvisorRequest, opts ...grpc.CallOption) (*GetAdvisorResponse, error)
	ApplyAsAdvisor(ctx context.Context, in *ApplyAsAdvisorRequest, opts ...grpc.CallOption) (*ApplyAsAdvisorResponse, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
}

type advisorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdvisorServiceClient(cc grpc.ClientConnInterface) AdvisorServiceClient {
	return &advisorServiceClient{cc}
}

func (c *advisorServiceClient) ListAdvisors(ctx context.Context, in *ListAdvisorsRequest, opts ...grpc.CallOption) (*ListAdvisorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdvisorsResponse)
	err := c.cc.Invoke(ctx, AdvisorService_ListAdvisors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advisorServiceClient) GetAdvisor(ctx context.Context, in *GetAdvisorRequest, opts ...grpc.CallOption) (*GetAdvisorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdvisorResponse)
	err := c.cc.Invoke(ctx, AdvisorService_GetAdvisor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advisorServiceClient) ApplyAsAdvisor(ctx context.Context, in *ApplyAsAdvisorRequest, opts ...grpc.CallOption) (*ApplyAsAdvisorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyAsAdvisorResponse)
	err := c.cc.Invoke(ctx, AdvisorService_ApplyAsAdvisor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advisorServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, AdvisorService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdvisorServiceServer is the server API for AdvisorService service.
// All implementations must embed UnimplementedAdvisorServiceServer
// for forward compatibility.
type AdvisorServiceServer interface {
	ListAdvisors(context.Context, *ListAdvisorsRequest) (*ListAdvisorsResponse, error)
	GetAdvisor(context.Context, *GetAdvisorRequest) (*GetAdvisorResponse, error)
	ApplyAsAdvisor(context.Context, *ApplyAsAdvisorRequest) (*ApplyAsAdvisorResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	mustEmbedUnimplementedAdvisorServiceServer()
}

// UnimplementedAdvisorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdvisorServiceServer struct{}

func (UnimplementedAdvisorServiceServer) ListAdvisors(context.Context, *ListAdvisorsRequest) (*ListAdvisorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdvisors not implemented")
}
func (UnimplementedAdvisorServiceServer) GetAdvisor(context.Context, *GetAdvisorRequest) (*GetAdvisorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdvisor not implemented")
}
func (UnimplementedAdvisorServiceServer) ApplyAsAdvisor(context.Context, *ApplyAsAdvisorRequest) (*ApplyAsAdvisorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyAsAdvisor not implemented")
}
func (UnimplementedAdvisorServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedAdvisorServiceServer) mustEmbedUnimplementedAdvisorServiceServer() {}
func (UnimplementedAdvisorServiceServer) testEmbeddedByValue()                        {}

// UnsafeAdvisorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdvisorServiceServer will
// result in compilation errors.
type UnsafeAdvisorServiceServer interface {
	mustEmbedUnimplementedAdvisorServiceServer()
}

func RegisterAdvisorServiceServer(s grpc.ServiceRegistrar, srv AdvisorServiceServer) {
	// If the following call panics, it indicates UnimplementedAdvisorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdvisorService_ServiceDesc, srv)
}

func _AdvisorService_ListAdvisors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdvisorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvisorServiceServer).ListAdvisors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvisorService_ListAdvisors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvisorServiceServer).ListAdvisors(ctx, req.(*ListAdvisorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvisorService_GetAdvisor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdvisorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvisorServiceServer).GetAdvisor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvisorService_GetAdvisor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvisorServiceServer).GetAdvisor(ctx, req.(*GetAdvisorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvisorService_ApplyAsAdvisor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyAsAdvisorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvisorServiceServer).ApplyAsAdvisor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvisorService_ApplyAsAdvisor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvisorServiceServer).ApplyAsAdvisor(ctx, req.(*ApplyAsAdvisorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvisorService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvisorServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvisorService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvisorServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdvisorService_ServiceDesc is the grpc.ServiceDesc for AdvisorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdvisorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loveguru.advisor.AdvisorService",
	HandlerType: (*AdvisorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAdvisors",
			Handler:    _AdvisorService_ListAdvisors_Handler,
		},
		{
			MethodName: "GetAdvisor",
			Handler:    _AdvisorService_GetAdvisor_Handler,
		},
		{
			MethodName: "ApplyAsAdvisor",
			Handler:    _AdvisorService_ApplyAsAdvisor_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _AdvisorService_UpdateProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/advisor.proto",
}
