// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: proto/advisor.proto

package advisor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "loveguru/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAdvisorsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RatingMin       float64                `protobuf:"fixed64,1,opt,name=rating_min,json=ratingMin,proto3" json:"rating_min,omitempty"`
	Languages       []string               `protobuf:"bytes,2,rep,name=languages,proto3" json:"languages,omitempty"`
	Specializations []string               `protobuf:"bytes,3,rep,name=specializations,proto3" json:"specializations,omitempty"`
	Sort            string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"` // top_rated, price, experience
	Limit           int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset          int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListAdvisorsRequest) Reset() {
	*x = ListAdvisorsRequest{}
	mi := &file_proto_advisor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdvisorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdvisorsRequest) ProtoMessage() {}

func (x *ListAdvisorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_advisor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdvisorsRequest.ProtoReflect.Descriptor instead.
func (*ListAdvisorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_advisor_proto_rawDescGZIP(), []int{0}
}

func (x *ListAdvisorsRequest) GetRatingMin() float64 {
	if x != nil {
		return x.RatingMin
	}
	return 0
}

func (x *ListAdvisorsRequest) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *ListAdvisorsRequest) GetSpecializations() []string {
	if x != nil {
		return x.Specializations
	}
	return nil
}

func (x *ListAdvisorsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListAdvisorsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAdvisorsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListAdvisorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Advisors      []*AdvisorWithRating   `protobuf:"bytes,1,rep,name=advisors,proto3" json:"advisors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdvisorsResponse) Reset() {
	*x = ListAdvisorsResponse{}
	mi := &file_proto_advisor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdvisorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdvisorsResponse) ProtoMessage() {}

func (x *ListAdvisorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_advisor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdvisorsResponse.ProtoReflect.Descriptor instead.
func (*ListAdvisorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_advisor_proto_rawDescGZIP(), []int{1}
}

func (x *ListAdvisorsResponse) GetAdvisors() []*AdvisorWithRating {
	if x != nil {
		return x.Advisors
	}
	return nil
}

type AdvisorWithRating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Advisor       *common.Advisor        `protobuf:"bytes,1,opt,name=advisor,proto3" json:"advisor,omitempty"`
	User          *common.User           `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	AverageRating float64                `protobuf:"fixed64,3,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvisorWithRating) Reset() {
	*x = AdvisorWithRating{}
	mi := &file_proto_advisor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvisorWithRating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvisorWithRating) ProtoMessage() {}

func (x *AdvisorWithRating) ProtoReflect() protoreflect.Message {
	mi := &file_proto_advisor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvisorWithRating.ProtoReflect.Descriptor instead.
func (*AdvisorWithRating) Descriptor() ([]byte, []int) {
	return file_proto_advisor_proto_rawDescGZIP(), []int{2}
}

func (x *AdvisorWithRating) GetAdvisor() *common.Advisor {
	if x != nil {
		return x.Advisor
	}
	return nil
}

func (x *AdvisorWithRating) GetUser() *common.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AdvisorWithRating) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

type GetAdvisorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdvisorRequest) Reset() {
	*x = GetAdvisorRequest{}
	mi := &file_proto_advisor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdvisorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdvisorRequest) ProtoMessage() {}

func (x *GetAdvisorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_advisor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdvisorRequest.ProtoReflect.Descriptor instead.
func (*GetAdvisorRequest) Descriptor() ([]byte, []int) {
	return file_proto_advisor_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdvisorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAdvisorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Advisor       *AdvisorWithRating     `protobuf:"bytes,1,opt,name=advisor,proto3" json:"advisor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdvisorResponse) Reset() {
	*x = GetAdvisorResponse{}
	mi := &file_proto_advisor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdvisorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdvisorResponse) ProtoMessage() {}

func (x *GetAdvisorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_advisor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdvisorResponse.ProtoReflect.Descriptor instead.
func (*GetAdvisorResponse) Descriptor() ([]byte, []int) {
	return file_proto_advisor_proto_rawDescGZIP(), []int{4}
}

func (x *GetAdvisorResponse) GetAdvisor() *AdvisorWithRating {
	if x != nil {
		return x.Advisor
	}
	return nil
}

type ApplyAsAdvisorRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Bio             string                 `protobuf:"bytes,1,opt,name=bio,proto3" json:"bio,omitempty"`
	ExperienceYears int32                  `protobuf:"varint,2,opt,name=experience_years,json=experienceYears,proto3" json:"experience_years,omitempty"`
	Languages       []string               `protobuf:"bytes,3,rep,name=languages,proto3" json:"languages,omitempty"`
	Specializations []string               `protobuf:"bytes,4,rep,name=specializations,proto3" json:"specializations,omitempty"`
	HourlyRate      float64                `protobuf:"fixed64,5,opt,name=hourly_rate,json=hourlyRate,proto3" json:"hourly_rate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplyAsAdvisorRequest) Reset() {
	*x = ApplyAsAdvisorRequest{}
	mi := &file_proto_advisor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyAsAdvisorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyAsAdvisorRequest) ProtoMessage() {}

func (x *ApplyAsAdvisorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_advisor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyAsAdvisorRequest.ProtoReflect.Descriptor instead.
func (*ApplyAsAdvisorRequest) Descriptor() ([]byte, []int) {
	return file_proto_advisor_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyAsAdvisorRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *ApplyAsAdvisorRequest) GetExperienceYears() int32 {
	if x != nil {
		return x.ExperienceYears
	}
	return 0
}

func (x *ApplyAsAdvisorRequest) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *ApplyAsAdvisorRequest) GetSpecializations() []string {
	if x != nil {
		return x.Specializations
	}
	return nil
}

func (x *ApplyAsAdvisorRequest) GetHourlyRate() float64 {
	if x != nil {
		return x.HourlyRate
	}
	return 0
}

type ApplyAsAdvisorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Advisor       *common.Advisor        `protobuf:"bytes,1,opt,name=advisor,proto3" json:"advisor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyAsAdvisorResponse) Reset() {
	*x = ApplyAsAdvisorResponse{}
	mi := &file_proto_advisor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyAsAdvisorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyAsAdvisorResponse) ProtoMessage() {}

func (x *ApplyAsAdvisorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_advisor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyAsAdvisorResponse.ProtoReflect.Descriptor instead.
func (*ApplyAsAdvisorResponse) Descriptor() ([]byte, []int) {
	return file_proto_advisor_proto_rawDescGZIP(), []int{6}
}

func (x *ApplyAsAdvisorResponse) GetAdvisor() *common.Advisor {
	if x != nil {
		return x.Advisor
	}
	return nil
}

type UpdateProfileRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Bio             string                 `protobuf:"bytes,1,opt,name=bio,proto3" json:"bio,omitempty"`
	ExperienceYears int32                  `protobuf:"varint,2,opt,name=experience_years,json=experienceYears,proto3" json:"experience_years,omitempty"`
	Languages       []string               `protobuf:"bytes,3,rep,name=languages,proto3" json:"languages,omitempty"`
	Specializations []string               `protobuf:"bytes,4,rep,name=specializations,proto3" json:"specializations,omitempty"`
	HourlyRate      float64                `protobuf:"fixed64,5,opt,name=hourly_rate,json=hourlyRate,proto3" json:"hourly_rate,omitempty"`
	Status          common.AdvisorStatus   `protobuf:"varint,6,opt,name=status,proto3,enum=loveguru.common.AdvisorStatus" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_proto_advisor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_advisor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_advisor_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateProfileRequest) GetExperienceYears() int32 {
	if x != nil {
		return x.ExperienceYears
	}
	return 0
}

func (x *UpdateProfileRequest) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *UpdateProfileRequest) GetSpecializations() []string {
	if x != nil {
		return x.Specializations
	}
	return nil
}

func (x *UpdateProfileRequest) GetHourlyRate() float64 {
	if x != nil {
		return x.HourlyRate
	}
	return 0
}

func (x *UpdateProfileRequest) GetStatus() common.AdvisorStatus {
	if x != nil {
		return x.Status
	}
	return common.AdvisorStatus(0)
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Advisor       *common.Advisor        `protobuf:"bytes,1,opt,name=advisor,proto3" json:"advisor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_proto_advisor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_advisor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_advisor_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProfileResponse) GetAdvisor() *common.Advisor {
	if x != nil {
		return x.Advisor
	}
	return nil
}

var File_proto_advisor_proto protoreflect.FileDescriptor

const file_proto_advisor_proto_rawDesc = "" +
	"\n" +
	"\x13proto/advisor.proto\x12\x10loveguru.advisor\x1a\x12proto/common.proto\"\xbe\x01\n" +
	"\x13ListAdvisorsRequest\x12\x1d\n" +
	"\n" +
	"rating_min\x18\x01 \x01(\x01R\tratingMin\x12\x1c\n" +
	"\tlanguages\x18\x02 \x03(\tR\tlanguages\x12(\n" +
	"\x0fspecializations\x18\x03 \x03(\tR\x0fspecializations\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"W\n" +
	"\x14ListAdvisorsResponse\x12?\n" +
	"\badvisors\x18\x01 \x03(\v2#.loveguru.advisor.AdvisorWithRatingR\badvisors\"\x99\x01\n" +
	"\x11AdvisorWithRating\x122\n" +
	"\aadvisor\x18\x01 \x01(\v2\x18.loveguru.common.AdvisorR\aadvisor\x12)\n" +
	"\x04user\x18\x02 \x01(\v2\x15.loveguru.common.UserR\x04user\x12%\n" +
	"\x0eaverage_rating\x18\x03 \x01(\x01R\raverageRating\"#\n" +
	"\x11GetAdvisorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	"\x12GetAdvisorResponse\x12=\n" +
	"\aadvisor\x18\x01 \x01(\v2#.loveguru.advisor.AdvisorWithRatingR\aadvisor\"\xbd\x01\n" +
	"\x15ApplyAsAdvisorRequest\x12\x10\n" +
	"\x03bio\x18\x01 \x01(\tR\x03bio\x12)\n" +
	"\x10experience_years\x18\x02 \x01(\x05R\x0fexperienceYears\x12\x1c\n" +
	"\tlanguages\x18\x03 \x03(\tR\tlanguages\x12(\n" +
	"\x0fspecializations\x18\x04 \x03(\tR\x0fspecializations\x12\x1f\n" +
	"\vhourly_rate\x18\x05 \x01(\x01R\n" +
	"hourlyRate\"L\n" +
	"\x16ApplyAsAdvisorResponse\x122\n" +
	"\aadvisor\x18\x01 \x01(\v2\x18.loveguru.common.AdvisorR\aadvisor\"\xf4\x01\n" +
	"\x14UpdateProfileRequest\x12\x10\n" +
	"\x03bio\x18\x01 \x01(\tR\x03bio\x12)\n" +
	"\x10experience_years\x18\x02 \x01(\x05R\x0fexperienceYears\x12\x1c\n" +
	"\tlanguages\x18\x03 \x03(\tR\tlanguages\x12(\n" +
	"\x0fspecializations\x18\x04 \x03(\tR\x0fspecializations\x12\x1f\n" +
	"\vhourly_rate\x18\x05 \x01(\x01R\n" +
	"hourlyRate\x126\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1e.loveguru.common.AdvisorStatusR\x06status\"K\n" +
	"\x15UpdateProfileResponse\x122\n" +
	"\aadvisor\x18\x01 \x01(\v2\x18.loveguru.common.AdvisorR\aadvisor2\x8f\x03\n" +
	"\x0eAdvisorService\x12]\n" +
	"\fListAdvisors\x12%.loveguru.advisor.ListAdvisorsRequest\x1a&.loveguru.advisor.ListAdvisorsResponse\x12W\n" +
	"\n" +
	"GetAdvisor\x12#.loveguru.advisor.GetAdvisorRequest\x1a$.loveguru.advisor.GetAdvisorResponse\x12c\n" +
	"\x0eApplyAsAdvisor\x12'.loveguru.advisor.ApplyAsAdvisorRequest\x1a(.loveguru.advisor.ApplyAsAdvisorResponse\x12`\n" +
	"\rUpdateProfile\x12&.loveguru.advisor.UpdateProfileRequest\x1a'.loveguru.advisor.UpdateProfileResponseB\x18Z\x16loveguru/proto/advisorb\x06proto3"

var (
	file_proto_advisor_proto_rawDescOnce sync.Once
	file_proto_advisor_proto_rawDescData []byte
)

func file_proto_advisor_proto_rawDescGZIP() []byte {
	file_proto_advisor_proto_rawDescOnce.Do(func() {
		file_proto_advisor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_advisor_proto_rawDesc), len(file_proto_advisor_proto_rawDesc)))
	})
	return file_proto_advisor_proto_rawDescData
}

var file_proto_advisor_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_advisor_proto_goTypes = []any{
	(*ListAdvisorsRequest)(nil),    // 0: loveguru.advisor.ListAdvisorsRequest
	(*ListAdvisorsResponse)(nil),   // 1: loveguru.advisor.ListAdvisorsResponse
	(*AdvisorWithRating)(nil),      // 2: loveguru.advisor.AdvisorWithRating
	(*GetAdvisorRequest)(nil),      // 3: loveguru.advisor.GetAdvisorRequest
	(*GetAdvisorResponse)(nil),     // 4: loveguru.advisor.GetAdvisorResponse
	(*ApplyAsAdvisorRequest)(nil),  // 5: loveguru.advisor.ApplyAsAdvisorRequest
	(*ApplyAsAdvisorResponse)(nil), // 6: loveguru.advisor.ApplyAsAdvisorResponse
	(*UpdateProfileRequest)(nil),   // 7: loveguru.advisor.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),  // 8: loveguru.advisor.UpdateProfileResponse
	(*common.Advisor)(nil),         // 9: loveguru.common.Advisor
	(*common.User)(nil),            // 10: loveguru.common.User
	(common.AdvisorStatus)(0),      // 11: loveguru.common.AdvisorStatus
}
var file_proto_advisor_proto_depIdxs = []int32{
	2,  // 0: loveguru.advisor.ListAdvisorsResponse.advisors:type_name -> loveguru.advisor.AdvisorWithRating
	9,  // 1: loveguru.advisor.AdvisorWithRating.advisor:type_name -> loveguru.common.Advisor
	10, // 2: loveguru.advisor.AdvisorWithRating.user:type_name -> loveguru.common.User
	2,  // 3: loveguru.advisor.GetAdvisorResponse.advisor:type_name -> loveguru.advisor.AdvisorWithRating
	9,  // 4: loveguru.advisor.ApplyAsAdvisorResponse.advisor:type_name -> loveguru.common.Advisor
	11, // 5: loveguru.advisor.UpdateProfileRequest.status:type_name -> loveguru.common.AdvisorStatus
	9,  // 6: loveguru.advisor.UpdateProfileResponse.advisor:type_name -> loveguru.common.Advisor
	0,  // 7: loveguru.advisor.AdvisorService.ListAdvisors:input_type -> loveguru.advisor.ListAdvisorsRequest
	3,  // 8: loveguru.advisor.AdvisorService.GetAdvisor:input_type -> loveguru.advisor.GetAdvisorRequest
	5,  // 9: loveguru.advisor.AdvisorService.ApplyAsAdvisor:input_type -> loveguru.advisor.ApplyAsAdvisorRequest
	7,  // 10: loveguru.advisor.AdvisorService.UpdateProfile:input_type -> loveguru.advisor.UpdateProfileRequest
	1,  // 11: loveguru.advisor.AdvisorService.ListAdvisors:output_type -> loveguru.advisor.ListAdvisorsResponse
	4,  // 12: loveguru.advisor.AdvisorService.GetAdvisor:output_type -> loveguru.advisor.GetAdvisorResponse
	6,  // 13: loveguru.advisor.AdvisorService.ApplyAsAdvisor:output_type -> loveguru.advisor.ApplyAsAdvisorResponse
	8,  // 14: loveguru.advisor.AdvisorService.UpdateProfile:output_type -> loveguru.advisor.UpdateProfileResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_advisor_proto_init() }
func file_proto_advisor_proto_init() {
	if File_proto_advisor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_advisor_proto_rawDesc), len(file_proto_advisor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_advisor_proto_goTypes,
		DependencyIndexes: file_proto_advisor_proto_depIdxs,
		MessageInfos:      file_proto_advisor_proto_msgTypes,
	}.Build()
	File_proto_advisor_proto = out.File
	file_proto_advisor_proto_goTypes = nil
	file_proto_advisor_proto_depIdxs = nil
}
