// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: proto/admin.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "loveguru/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminFlag struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReportedBy        string                 `protobuf:"bytes,2,opt,name=reported_by,json=reportedBy,proto3" json:"reported_by,omitempty"`
	ReportedUserId    string                 `protobuf:"bytes,3,opt,name=reported_user_id,json=reportedUserId,proto3" json:"reported_user_id,omitempty"`
	ReportedAdvisorId string                 `protobuf:"bytes,4,opt,name=reported_advisor_id,json=reportedAdvisorId,proto3" json:"reported_advisor_id,omitempty"`
	Reason            string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	SessionId         string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status            string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AdminFlag) Reset() {
	*x = AdminFlag{}
	mi := &file_proto_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFlag) ProtoMessage() {}

func (x *AdminFlag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFlag.ProtoReflect.Descriptor instead.
func (*AdminFlag) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminFlag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminFlag) GetReportedBy() string {
	if x != nil {
		return x.ReportedBy
	}
	return ""
}

func (x *AdminFlag) GetReportedUserId() string {
	if x != nil {
		return x.ReportedUserId
	}
	return ""
}

func (x *AdminFlag) GetReportedAdvisorId() string {
	if x != nil {
		return x.ReportedAdvisorId
	}
	return ""
}

func (x *AdminFlag) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AdminFlag) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AdminFlag) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AdminFlag) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetPendingAdvisorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingAdvisorsRequest) Reset() {
	*x = GetPendingAdvisorsRequest{}
	mi := &file_proto_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingAdvisorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingAdvisorsRequest) ProtoMessage() {}

func (x *GetPendingAdvisorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingAdvisorsRequest.ProtoReflect.Descriptor instead.
func (*GetPendingAdvisorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetPendingAdvisorsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPendingAdvisorsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetPendingAdvisorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Advisors      []*common.Advisor      `protobuf:"bytes,1,rep,name=advisors,proto3" json:"advisors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingAdvisorsResponse) Reset() {
	*x = GetPendingAdvisorsResponse{}
	mi := &file_proto_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingAdvisorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingAdvisorsResponse) ProtoMessage() {}

func (x *GetPendingAdvisorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingAdvisorsResponse.ProtoReflect.Descriptor instead.
func (*GetPendingAdvisorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{2}
}

func (x *GetPendingAdvisorsResponse) GetAdvisors() []*common.Advisor {
	if x != nil {
		return x.Advisors
	}
	return nil
}

type ApproveAdvisorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdvisorId     string                 `protobuf:"bytes,1,opt,name=advisor_id,json=advisorId,proto3" json:"advisor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveAdvisorRequest) Reset() {
	*x = ApproveAdvisorRequest{}
	mi := &file_proto_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveAdvisorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveAdvisorRequest) ProtoMessage() {}

func (x *ApproveAdvisorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveAdvisorRequest.ProtoReflect.Descriptor instead.
func (*ApproveAdvisorRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ApproveAdvisorRequest) GetAdvisorId() string {
	if x != nil {
		return x.AdvisorId
	}
	return ""
}

type ApproveAdvisorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveAdvisorResponse) Reset() {
	*x = ApproveAdvisorResponse{}
	mi := &file_proto_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveAdvisorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveAdvisorResponse) ProtoMessage() {}

func (x *ApproveAdvisorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveAdvisorResponse.ProtoReflect.Descriptor instead.
func (*ApproveAdvisorResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ApproveAdvisorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetFlagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlagsRequest) Reset() {
	*x = GetFlagsRequest{}
	mi := &file_proto_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlagsRequest) ProtoMessage() {}

func (x *GetFlagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlagsRequest.ProtoReflect.Descriptor instead.
func (*GetFlagsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{5}
}

func (x *GetFlagsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFlagsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetFlagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         []*AdminFlag           `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlagsResponse) Reset() {
	*x = GetFlagsResponse{}
	mi := &file_proto_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlagsResponse) ProtoMessage() {}

func (x *GetFlagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlagsResponse.ProtoReflect.Descriptor instead.
func (*GetFlagsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{6}
}

func (x *GetFlagsResponse) GetFlags() []*AdminFlag {
	if x != nil {
		return x.Flags
	}
	return nil
}

type BlockUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserRequest) Reset() {
	*x = BlockUserRequest{}
	mi := &file_proto_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserRequest) ProtoMessage() {}

func (x *BlockUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserRequest.ProtoReflect.Descriptor instead.
func (*BlockUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{7}
}

func (x *BlockUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BlockUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserResponse) Reset() {
	*x = BlockUserResponse{}
	mi := &file_proto_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserResponse) ProtoMessage() {}

func (x *BlockUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserResponse.ProtoReflect.Descriptor instead.
func (*BlockUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{8}
}

func (x *BlockUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_admin_proto protoreflect.FileDescriptor

const file_proto_admin_proto_rawDesc = "" +
	"\n" +
	"\x11proto/admin.proto\x12\x0eloveguru.admin\x1a\x12proto/common.proto\"\x84\x02\n" +
	"\tAdminFlag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vreported_by\x18\x02 \x01(\tR\n" +
	"reportedBy\x12(\n" +
	"\x10reported_user_id\x18\x03 \x01(\tR\x0ereportedUserId\x12.\n" +
	"\x13reported_advisor_id\x18\x04 \x01(\tR\x11reportedAdvisorId\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"I\n" +
	"\x19GetPendingAdvisorsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"R\n" +
	"\x1aGetPendingAdvisorsResponse\x124\n" +
	"\badvisors\x18\x01 \x03(\v2\x18.loveguru.common.AdvisorR\badvisors\"6\n" +
	"\x15ApproveAdvisorRequest\x12\x1d\n" +
	"\n" +
	"advisor_id\x18\x01 \x01(\tR\tadvisorId\"2\n" +
	"\x16ApproveAdvisorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"?\n" +
	"\x0fGetFlagsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"C\n" +
	"\x10GetFlagsResponse\x12/\n" +
	"\x05flags\x18\x01 \x03(\v2\x19.loveguru.admin.AdminFlagR\x05flags\"+\n" +
	"\x10BlockUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"-\n" +
	"\x11BlockUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xfd\x02\n" +
	"\fAdminService\x12k\n" +
	"\x12GetPendingAdvisors\x12).loveguru.admin.GetPendingAdvisorsRequest\x1a*.loveguru.admin.GetPendingAdvisorsResponse\x12_\n" +
	"\x0eApproveAdvisor\x12%.loveguru.admin.ApproveAdvisorRequest\x1a&.loveguru.admin.ApproveAdvisorResponse\x12M\n" +
	"\bGetFlags\x12\x1f.loveguru.admin.GetFlagsRequest\x1a .loveguru.admin.GetFlagsResponse\x12P\n" +
	"\tBlockUser\x12 .loveguru.admin.BlockUserRequest\x1a!.loveguru.admin.BlockUserResponseB\x16Z\x14loveguru/proto/adminb\x06proto3"

var (
	file_proto_admin_proto_rawDescOnce sync.Once
	file_proto_admin_proto_rawDescData []byte
)

func file_proto_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)))
	})
	return file_proto_admin_proto_rawDescData
}

var file_proto_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_admin_proto_goTypes = []any{
	(*AdminFlag)(nil),                  // 0: loveguru.admin.AdminFlag
	(*GetPendingAdvisorsRequest)(nil),  // 1: loveguru.admin.GetPendingAdvisorsRequest
	(*GetPendingAdvisorsResponse)(nil), // 2: loveguru.admin.GetPendingAdvisorsResponse
	(*ApproveAdvisorRequest)(nil),      // 3: loveguru.admin.ApproveAdvisorRequest
	(*ApproveAdvisorResponse)(nil),     // 4: loveguru.admin.ApproveAdvisorResponse
	(*GetFlagsRequest)(nil),            // 5: loveguru.admin.GetFlagsRequest
	(*GetFlagsResponse)(nil),           // 6: loveguru.admin.GetFlagsResponse
	(*BlockUserRequest)(nil),           // 7: loveguru.admin.BlockUserRequest
	(*BlockUserResponse)(nil),          // 8: loveguru.admin.BlockUserResponse
	(*common.Advisor)(nil),             // 9: loveguru.common.Advisor
}
var file_proto_admin_proto_depIdxs = []int32{
	9, // 0: loveguru.admin.GetPendingAdvisorsResponse.advisors:type_name -> loveguru.common.Advisor
	0, // 1: loveguru.admin.GetFlagsResponse.flags:type_name -> loveguru.admin.AdminFlag
	1, // 2: loveguru.admin.AdminService.GetPendingAdvisors:input_type -> loveguru.admin.GetPendingAdvisorsRequest
	3, // 3: loveguru.admin.AdminService.ApproveAdvisor:input_type -> loveguru.admin.ApproveAdvisorRequest
	5, // 4: loveguru.admin.AdminService.GetFlags:input_type -> loveguru.admin.GetFlagsRequest
	7, // 5: loveguru.admin.AdminService.BlockUser:input_type -> loveguru.admin.BlockUserRequest
	2, // 6: loveguru.admin.AdminService.GetPendingAdvisors:output_type -> loveguru.admin.GetPendingAdvisorsResponse
	4, // 7: loveguru.admin.AdminService.ApproveAdvisor:output_type -> loveguru.admin.ApproveAdvisorResponse
	6, // 8: loveguru.admin.AdminService.GetFlags:output_type -> loveguru.admin.GetFlagsResponse
	8, // 9: loveguru.admin.AdminService.BlockUser:output_type -> loveguru.admin.BlockUserResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_admin_proto_init() }
func file_proto_admin_proto_init() {
	if File_proto_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_proto_depIdxs,
		MessageInfos:      file_proto_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_proto = out.File
	file_proto_admin_proto_goTypes = nil
	file_proto_admin_proto_depIdxs = nil
}
