// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: proto/call.proto

package call

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "loveguru/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdvisorId     string                 `protobuf:"bytes,1,opt,name=advisor_id,json=advisorId,proto3" json:"advisor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_call_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetAdvisorId() string {
	if x != nil {
		return x.AdvisorId
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *common.Session        `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	CallToken     string                 `protobuf:"bytes,2,opt,name=call_token,json=callToken,proto3" json:"call_token,omitempty"` // from VoIP provider
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_proto_call_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSession() *common.Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *CreateSessionResponse) GetCallToken() string {
	if x != nil {
		return x.CallToken
	}
	return ""
}

func (x *CreateSessionResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type EndCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndCallRequest) Reset() {
	*x = EndCallRequest{}
	mi := &file_proto_call_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCallRequest) ProtoMessage() {}

func (x *EndCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCallRequest.ProtoReflect.Descriptor instead.
func (*EndCallRequest) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{2}
}

func (x *EndCallRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type EndCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndCallResponse) Reset() {
	*x = EndCallResponse{}
	mi := &file_proto_call_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCallResponse) ProtoMessage() {}

func (x *EndCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCallResponse.ProtoReflect.Descriptor instead.
func (*EndCallResponse) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{3}
}

func (x *EndCallResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallRequest) Reset() {
	*x = GetCallRequest{}
	mi := &file_proto_call_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallRequest) ProtoMessage() {}

func (x *GetCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallRequest.ProtoReflect.Descriptor instead.
func (*GetCallRequest) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{4}
}

func (x *GetCallRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *common.Session        `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"` // additional call details if needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallResponse) Reset() {
	*x = GetCallResponse{}
	mi := &file_proto_call_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallResponse) ProtoMessage() {}

func (x *GetCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallResponse.ProtoReflect.Descriptor instead.
func (*GetCallResponse) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{5}
}

func (x *GetCallResponse) GetSession() *common.Session {
	if x != nil {
		return x.Session
	}
	return nil
}

var File_proto_call_proto protoreflect.FileDescriptor

const file_proto_call_proto_rawDesc = "" +
	"\n" +
	"\x10proto/call.proto\x12\rloveguru.call\x1a\x12proto/common.proto\"5\n" +
	"\x14CreateSessionRequest\x12\x1d\n" +
	"\n" +
	"advisor_id\x18\x01 \x01(\tR\tadvisorId\"\x83\x01\n" +
	"\x15CreateSessionResponse\x122\n" +
	"\asession\x18\x01 \x01(\v2\x18.loveguru.common.SessionR\asession\x12\x1d\n" +
	"\n" +
	"call_token\x18\x02 \x01(\tR\tcallToken\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\"/\n" +
	"\x0eEndCallRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"+\n" +
	"\x0fEndCallResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x0eGetCallRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"E\n" +
	"\x0fGetCallResponse\x122\n" +
	"\asession\x18\x01 \x01(\v2\x18.loveguru.common.SessionR\asession2\xfd\x01\n" +
	"\vCallService\x12Z\n" +
	"\rCreateSession\x12#.loveguru.call.CreateSessionRequest\x1a$.loveguru.call.CreateSessionResponse\x12H\n" +
	"\aEndCall\x12\x1d.loveguru.call.EndCallRequest\x1a\x1e.loveguru.call.EndCallResponse\x12H\n" +
	"\aGetCall\x12\x1d.loveguru.call.GetCallRequest\x1a\x1e.loveguru.call.GetCallResponseB\x15Z\x13loveguru/proto/callb\x06proto3"

var (
	file_proto_call_proto_rawDescOnce sync.Once
	file_proto_call_proto_rawDescData []byte
)

func file_proto_call_proto_rawDescGZIP() []byte {
	file_proto_call_proto_rawDescOnce.Do(func() {
		file_proto_call_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_call_proto_rawDesc), len(file_proto_call_proto_rawDesc)))
	})
	return file_proto_call_proto_rawDescData
}

var file_proto_call_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_call_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),  // 0: loveguru.call.CreateSessionRequest
	(*CreateSessionResponse)(nil), // 1: loveguru.call.CreateSessionResponse
	(*EndCallRequest)(nil),        // 2: loveguru.call.EndCallRequest
	(*EndCallResponse)(nil),       // 3: loveguru.call.EndCallResponse
	(*GetCallRequest)(nil),        // 4: loveguru.call.GetCallRequest
	(*GetCallResponse)(nil),       // 5: loveguru.call.GetCallResponse
	(*common.Session)(nil),        // 6: loveguru.common.Session
}
var file_proto_call_proto_depIdxs = []int32{
	6, // 0: loveguru.call.CreateSessionResponse.session:type_name -> loveguru.common.Session
	6, // 1: loveguru.call.GetCallResponse.session:type_name -> loveguru.common.Session
	0, // 2: loveguru.call.CallService.CreateSession:input_type -> loveguru.call.CreateSessionRequest
	2, // 3: loveguru.call.CallService.EndCall:input_type -> loveguru.call.EndCallRequest
	4, // 4: loveguru.call.CallService.GetCall:input_type -> loveguru.call.GetCallRequest
	1, // 5: loveguru.call.CallService.CreateSession:output_type -> loveguru.call.CreateSessionResponse
	3, // 6: loveguru.call.CallService.EndCall:output_type -> loveguru.call.EndCallResponse
	5, // 7: loveguru.call.CallService.GetCall:output_type -> loveguru.call.GetCallResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_call_proto_init() }
func file_proto_call_proto_init() {
	if File_proto_call_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_call_proto_rawDesc), len(file_proto_call_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_call_proto_goTypes,
		DependencyIndexes: file_proto_call_proto_depIdxs,
		MessageInfos:      file_proto_call_proto_msgTypes,
	}.Build()
	File_proto_call_proto = out.File
	file_proto_call_proto_goTypes = nil
	file_proto_call_proto_depIdxs = nil
}
