// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type AdminFlag struct {
	ID                uuid.UUID      `json:"id"`
	ReportedBy        uuid.UUID      `json:"reported_by"`
	ReportedUserID    uuid.NullUUID  `json:"reported_user_id"`
	ReportedAdvisorID uuid.NullUUID  `json:"reported_advisor_id"`
	Reason            string         `json:"reason"`
	SessionID         uuid.NullUUID  `json:"session_id"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	Status            sql.NullString `json:"status"`
}

type Advisor struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	Bio             sql.NullString `json:"bio"`
	ExperienceYears sql.NullInt32  `json:"experience_years"`
	Languages       []string       `json:"languages"`
	Specializations []string       `json:"specializations"`
	IsVerified      sql.NullBool   `json:"is_verified"`
	HourlyRate      sql.NullString `json:"hourly_rate"`
	Status          sql.NullString `json:"status"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type AiInteraction struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Prompt    string       `json:"prompt"`
	Response  string       `json:"response"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type CallFeedbackPrompt struct {
	ID                 uuid.UUID      `json:"id"`
	SessionID          uuid.UUID      `json:"session_id"`
	UserID             uuid.UUID      `json:"user_id"`
	AdvisorID          uuid.UUID      `json:"advisor_id"`
	PromptSentAt       sql.NullTime   `json:"prompt_sent_at"`
	ResponseReceivedAt sql.NullTime   `json:"response_received_at"`
	Rating             sql.NullInt32  `json:"rating"`
	FeedbackText       sql.NullString `json:"feedback_text"`
}

type CallLog struct {
	ID              uuid.UUID      `json:"id"`
	SessionID       uuid.UUID      `json:"session_id"`
	ExternalCallID  sql.NullString `json:"external_call_id"`
	StartedAt       sql.NullTime   `json:"started_at"`
	EndedAt         sql.NullTime   `json:"ended_at"`
	DurationSeconds sql.NullInt32  `json:"duration_seconds"`
	Status          sql.NullString `json:"status"`
	StatusUpdate    sql.NullString `json:"status_update"`
	StatusTimestamp sql.NullTime   `json:"status_timestamp"`
}

type ChatMessage struct {
	ID         uuid.UUID    `json:"id"`
	SessionID  uuid.UUID    `json:"session_id"`
	SenderType string       `json:"sender_type"`
	SenderID   uuid.UUID    `json:"sender_id"`
	Content    string       `json:"content"`
	CreatedAt  sql.NullTime `json:"created_at"`
	IsRead     sql.NullBool `json:"is_read"`
}

type Faq struct {
	ID        uuid.UUID    `json:"id"`
	Question  string       `json:"question"`
	Answer    string       `json:"answer"`
	Category  string       `json:"category"`
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Rating struct {
	ID         uuid.UUID      `json:"id"`
	SessionID  uuid.UUID      `json:"session_id"`
	UserID     uuid.UUID      `json:"user_id"`
	AdvisorID  uuid.UUID      `json:"advisor_id"`
	Rating     int32          `json:"rating"`
	ReviewText sql.NullString `json:"review_text"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type Session struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	AdvisorID uuid.NullUUID  `json:"advisor_id"`
	Type      string         `json:"type"`
	StartedAt sql.NullTime   `json:"started_at"`
	EndedAt   sql.NullTime   `json:"ended_at"`
	Status    sql.NullString `json:"status"`
}

type Specialization struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Category    string         `json:"category"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Email        sql.NullString `json:"email"`
	Phone        sql.NullString `json:"phone"`
	PasswordHash string         `json:"password_hash"`
	DisplayName  string         `json:"display_name"`
	Role         string         `json:"role"`
	Gender       sql.NullString `json:"gender"`
	Dob          sql.NullTime   `json:"dob"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	IsActive     sql.NullBool   `json:"is_active"`
	FcmToken     sql.NullString `json:"fcm_token"`
	ApnsToken    sql.NullString `json:"apns_token"`
	DeviceType   sql.NullString `json:"device_type"`
}
