// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	ApproveAdvisor(ctx context.Context, id uuid.UUID) error
	BlockUser(ctx context.Context, id uuid.UUID) error
	CreateAdvisor(ctx context.Context, arg CreateAdvisorParams) (Advisor, error)
	CreateCallSession(ctx context.Context, arg CreateCallSessionParams) (Session, error)
	CreateRating(ctx context.Context, arg CreateRatingParams) (Rating, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	EndCall(ctx context.Context, id uuid.UUID) error
	GetAdvisorByID(ctx context.Context, id uuid.UUID) (GetAdvisorByIDRow, error)
	GetAdvisorByUserID(ctx context.Context, userID uuid.UUID) (Advisor, error)
	GetAdvisorRatings(ctx context.Context, arg GetAdvisorRatingsParams) ([]Rating, error)
	GetFlags(ctx context.Context, arg GetFlagsParams) ([]AdminFlag, error)
	GetMessages(ctx context.Context, arg GetMessagesParams) ([]ChatMessage, error)
	GetPendingAdvisors(ctx context.Context, arg GetPendingAdvisorsParams) ([]GetPendingAdvisorsRow, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetUserByEmail(ctx context.Context, email sql.NullString) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone sql.NullString) (User, error)
	GetUserSessions(ctx context.Context, arg GetUserSessionsParams) ([]Session, error)
	InsertAIInteraction(ctx context.Context, arg InsertAIInteractionParams) (AiInteraction, error)
	InsertCallLog(ctx context.Context, arg InsertCallLogParams) (CallLog, error)
	InsertMessage(ctx context.Context, arg InsertMessageParams) (ChatMessage, error)
	ListAdvisors(ctx context.Context, arg ListAdvisorsParams) ([]ListAdvisorsRow, error)
	UpdateAdvisor(ctx context.Context, arg UpdateAdvisorParams) (Advisor, error)
	UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
